language: java
before_script:
- unset _JAVA_OPTIONS
- cd finish/system
- chmod +x ../../scripts/travisTest.sh
script:
- ../scripts/travisTest.sh
after_script:
- logsPath=$(find . -name "console.log" | sed "s/console.log//g");
- build=$(grep "Open Liberty" $logsPath/console.log | cut -d" " -f5 | cut -d")" -f1 );
- release=$( echo "$build" | cut -d'/' -f1); 
- number=$(echo "$build" | cut -d'/' -f2); 
- ol_jv=$(grep -i "version" $logsPath/console.log);
- jv=$(printf '%s\n' "${ol_jv//$' on '/$'\n'}" | sed '2q;d'); 
- echo -e "\n"\
  "\033[1;34m Open Liberty release:\033[0m\033[1;36m $release \033[0m \n"\
  "\033[1;34m Open Liberty build number:\033[0m\033[1;36m $number \033[0m \n"\
  "\033[1;34m Java version:\033[0m\033[1;36m $jv \033[0m \n"
- cd $logsPath;
- repo_name=$(echo "$TRAVIS_REPO_SLUG" | sed -e "s/\//-/g"); 
- if [ "$TRAVIS_TEST_RESULT" -eq 0 ]; then RESULT="passed"; else RESULT="failed"; fi;
- echo -e "\033[1;34m result:\033[0m\033[1;36m $RESULT \033[0m \n"
- serverlogsarchive="$repo_name-$TRAVIS_BUILD_NUMBER-$RESULT.zip";
- if [ "$TRAVIS_TEST_RESULT" -eq 0 ]; then echo skipped to zip $serverlogsarchive; else zip -r "$serverlogsarchive" .; fi;
- if [ "$TRAVIS_TEST_RESULT" -eq 0 ]; then echo skipped upload; else curl -H "$JFROG_TOKEN" -T "$serverlogsarchive" "https://na.artifactory.swg-devops.com/artifactory/hyc-openliberty-guides-files-generic-local/"; fi;
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: mr3KuuI35DXbCA/ifU3wzsLYEbLriK6CAjdRrkt+ksfdeVHOMc8PvvCFcJovi9xSz/Oh/DWKBdqLwJ+bb1XUBUY1O5V0wTjczfIzIyXOiNy8pCrzwgGkmVVKCgkS1B+U4QX4+6vPl1yO8jThVEH4u4vpwcOIUQwWF23rRQa1rwiVlEorkloUvahYK4jeJ4K5/qU1f+ajX4bzkaTEGYY1sOFRyy6tUlAXupVAGjtyvZZRshiHmVzT+vNkR3OK9ImrOBg+tp1axSSSPuvNxSeqySjmgue3yL+F+hFiNfj6+FDwJm8r6O06aj0kbiuZBkulJuL76OPm6XajkmNdjbfxHlctUOwWLcz0dNT+6U24Ig+bdLOCxTGhQ8nzd3JDXauZdS9zyGoxqYbes4OvvJcrbkSOBYLILzPRDDpvEI8VE/VKxGtnkjf86K1dvbqvtDFeqIc9PFz+FGIIESQBi0nUPIOz6KLAKkBlR75XM133gJion97q3Qj85tSk7BJ7tX4rkSPjzxUsJ/gbMyk5ttHon2xdUFPObIXIZEGMJChQc+tMjmVEdrfjk4Rxm1ohz3FlXLmqMF+htaZWu8rtG1lUrZhdDjnyK8RrC1BHENDXHLCUTeo5ijQQD/PSypUSKemh3Zt8VZXznbjBORvGDDANjrtqhgOOKUCxuk3tlfjkipo=
    on_success: never
    on_failure: always
branches:
  only:
  - master
